language: python
python:
  - "3.5"
install:
  - pip3 install awscli boto3 --ignore-installed six
script:
  - export PYTHONPATH=/usr/lib/python3/dist-packages:/usr/local/lib/python3.5/dist-packages && scripts/kali_cron
