version: 2
jobs:
  build:
    docker:
      - image: python:3.6

    steps:
      - checkout
      - run: pip3 install awscli boto3 --ignore-installed six
      - run: ./scripts/kali_cron
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "42 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
