#!/usr/bin/env bash
#source /etc/environment

[[ -z "$GO_SERVER_URL" ]] || exit 0
# ensure we're being triggered by the timer
#[[ $GO_TRIGGER_USER == "timer" ]] || [[ $TRAVIS_EVENT_TYPE == "cron" ]] || exit 0

if [[ $(date +%u) -eq 2 ]]; then
    scripts/kali.py "${CHANDIKA}" "${CHANDIKA_API_KEY}"
fi

if [[ $(date +%u) -eq 7 ]]; then
    python3 scripts/kali.py --no-dry-run "${CHANDIKA}" "${CHANDIKA_API_KEY}"
fi
