#!/usr/bin/env bash
source /etc/environment

# ensure we're being triggered by the timer
[[ $GO_TRIGGER_USER == "timer" ]] || exit 0

if [[ $(date +%u) -eq 4 ]]; then
    python3 scripts/kali.py "${CHANDIKA}" "${CHANDIKA_API_KEY}"
fi

if [[ $(date +%u) -eq 7 ]]; then
    python3 scripts/kali.py --no-dry-run "${CHANDIKA}" "${CHANDIKA_API_KEY}"
fi
